title: Media Organizer
colors:
  main: '#141414'
  sub: '#232323'
  special: '#5c0f80'
  special_alt: '#b435f0'
  alt: '#3c6fc2'
  font: '#ffffff'
fonts:
  xxsmall: ['Constantia', 11]
  xsmall: ['Constantia', 12]
  small: ['Constantia', 13]
  medium: ['Constantia', 14]
  large: ['Constantia', 18]
  xlarge: ['Constantia', 22]
  xxlarge: ['Constantia', 40]
required_paths:
  - downloads
  - media