media_extensions:
- mp4
- mkv
- avi
- flv
- wmv
- webm
- m4p
- mov
- m4v
- mpg
- 3gp
paths:
  downloads: C:/Users/Justango/Documents/GitRepos/practice-projects/Python3_Projects/Organize_Media/resources/Downloads
  media: C:/Users/Justango/Documents/GitRepos/practice-projects/Python3_Projects/Organize_Media/resources/Media
